version: "3.3"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - "8001:80"
        links:
            - fpm
        volumes:
            - ./:/var/www/laravel-authors-books-crud
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            - ./:/var/www/laravel-authors-books-crud
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        links:
            - postgresql
    postgresql:
        build:
            context: .
            dockerfile: docker/Postgres.Dockerfile
        ports:
            - "54321:5432"
        environment:
            POSTGRES_DB: "laravel-authors-books-crud"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "root"
